import Link from 'next/link'
import './globals.css'
import { Control } from './Control';

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by soyeon',
}
export default async function RootLayout({ children }) {

    // fetch('http://localhost:9999/topics')
    // .then(resp=>resp.json())
    // .then(result=>{
    //     setTopics(result);
    // });
const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', { cache: 'no-store'}) ;
const topics = await resp.json();

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <p>리스트 시작</p>
        <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        <p>여기까지 글 목록</p>
        <hr></hr>
        {children}
        <hr></hr>
        <Control />
      </body>
    </html>
  )
}
